<?php
	$storeID = Mage::app()->getStore()->getStoreId();
    $options = $this->getStoreOptionValues($storeID);
?>

<?php if (count($this->getOptionValues($storeID)) < 1): ?>

	<div>
		<ul class="messages">
		    <li class="notice-msg">
		        <ul>
		            <li><?php echo Mage::helper('catalog')->__('If you do not specify options you cannot set up swatches.') ?></li>
		        </ul>
		    </li>
		</ul>
	</div>

<?php else: ?>

	<div class="entity-edit">
	    <div class="entry-edit-head">
	        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Enable Swatches') ?></h4>
	    </div>
	    <div class="box">
            <div class="hor-scroll">
	            <table class="form-list" cellspacing="0" id="table_swatchenabled">
	                <tr>
	                	<td class="label">
	                		<label for="swatch[product_view]">Product View</label>
	                	</td>
	                	<td class="value">
	                		<select id="swatch-enable-productview" name="swatch[product_view]" class="select">
	                			<option value="1">Yes</option>
	                			<option value="0" selected="selected">No</option>
	                		</select>
	                	</td>
	                </tr>
	                <tr>
	                	<td class="label">
	                		<label for="swatch[catalog_view]">Catalog View</label>
	                	</td>
	                	<td class="value">
	                		<select id="swatch-enable-catalogview" name="swatch[catalog_view]" class="select">
	                			<option value="1">Yes</option>
	                			<option value="0" selected="selected">No</option>
	                		</select>
	                	</td>
	                </tr>
	            </table>
            </div>
	    </div>
	</div>
	<br/>
	<div class="entity-edit">
	    <div class="entry-edit-head">
	        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Swatch Images') ?></h4>
	    </div>
	    <div class="box">
            <div class="hor-scroll">
            	<div class="grid">
		            <table class="data border" cellspacing="0" id="attribute-swatchimages-grid" width="100%">
						<colgroup>
							<col width="1" />
							<col width="1" />
							<col />
							<col width="1" />
						</colgroup>

		            	<tr class="headings">
		            		<th>Image</th>
	        				<th>Option Label</th>
	        				<th>Upload Image</th>
	        				<th>Remove Image</th>
	        			</tr>
		                
	                	<?php foreach ($this->getOptionValues($storeID) as $option): ?>
		                	<tr>
		                		
		                		<?php if ($option->getPath() == ''): ?>
		                			<td>No image</td>
		                		<?php else: ?>
		                			<td style="text-align:center;padding-top:5px;">
		                				<img width="30" height="30" src="<?php echo Mage::getBaseUrl('media') . 'attribute_swatches/' . $option->getPath(); ?>" />
		                			</td>
		                		<?php endif; ?>

		                		<td>
		                			<?php echo $option->getValue(); ?>
		                			<input type="hidden" name="swatch[<?php echo $option->getId(); ?>][store_id]" value="<?php echo $storeID; ?>" />
		                		</td>
		                		<td><input type="file" name="swatch-<?php echo $option->getId(); ?>" /></td>
		                		<td style="text-align:center;">
		                			<?php if ($option->getSwatchId()): ?>
		                			<input type="checkbox" name="swatch[<?php echo $option->getSwatchId(); ?>][remove]" value="1" />
		                			<?php endif; ?>
		                		</td>
		                	</tr>
	                	<?php endforeach; ?>
		            </table>
		        </div>
            </div>
	    </div>
	</div>

<?php endif; ?>